language: python
python:
-   '2.7'
-   '3.4'
-   '3.5'
-   '3.6'
before_install:
- travis_retry pip install --upgrade pip
- travis_retry pip install ipython
install:
- travis_retry pip install --upgrade pip
- travis_retry pip install ipython
- travis_retry pip install tox
script:
-   tox -e $(echo py$TRAVIS_PYTHON_VERSION | tr -d .)